export const VEGGIE_METADATA = {
  Tomato: {
    spacing: 18,
    height: 48,
    color: "#ef4444",
    icon: "🍅",
    companions: ["Basil", "Onion", "Carrot"],
    antagonists: ["Kale"],
    habit: "Tall & Vertical",
    root: "Deep (> 12\")",
  },
  Carrot: {
    spacing: 3,
    height: 12,
    color: "#f97316",
    icon: "🥕",
    companions: ["Tomato", "Onion", "Lettuce"],
    antagonists: [],
    habit: "Underground Root",
    root: "Medium (6-12\")",
  },
  Lettuce: {
    spacing: 6,
    height: 8,
    color: "#4ade80",
    icon: "🥬",
    companions: ["Carrot", "Radish", "Cucumber"],
    antagonists: [],
    habit: "Ground Cover",
    root: "Shallow (< 6\")",
  },
  Pepper: {
    spacing: 15,
    height: 24,
    color: "#facc15",
    icon: "🫑",
    companions: ["Basil", "Onion"],
    antagonists: [],
    habit: "Bushy & Medium",
    root: "Medium (6-12\")",
  },
  Kale: {
    spacing: 12,
    height: 18,
    color: "#166534",
    icon: "🥬",
    companions: ["Onion", "Lettuce"],
    antagonists: ["Tomato"],
    habit: "Bushy & Medium",
    root: "Medium (6-12\")",
  },
  Cucumber: {
    spacing: 12,
    height: 12,
    color: "#22c55e",
    icon: "🥒",
    companions: ["Radish", "Lettuce"],
    antagonists: ["Basil"],
    habit: "Climbing Vine",
    root: "Medium (6-12\")",
  },
  Zucchini: {
    spacing: 24,
    height: 24,
    color: "#15803d",
    icon: "🥒",
    companions: ["Radish"],
    antagonists: [],
    habit: "Bushy & Medium",
    root: "Medium (6-12\")",
  },
  Onion: {
    spacing: 4,
    height: 12,
    color: "#e2e8f0",
    icon: "🧅",
    companions: ["Tomato", "Carrot", "Pepper"],
    antagonists: [],
    habit: "Underground Root",
    root: "Shallow (< 6\")",
  },
  Radish: {
    spacing: 2,
    height: 6,
    color: "#db2777",
    icon: "🏮",
    companions: ["Lettuce", "Cucumber", "Zucchini"],
    antagonists: [],
    habit: "Underground Root",
    root: "Shallow (< 6\")",
  },
  Basil: {
    spacing: 10,
    height: 15,
    color: "#86efac",
    icon: "🌿",
    companions: ["Tomato", "Pepper"],
    antagonists: ["Cucumber"],
    habit: "Bushy & Medium",
    root: "Shallow (< 6\")",
  },
};

export const VEGGIE_TYPES = Object.keys(VEGGIE_METADATA);
