export const PLANT_CATALOG = {
  plants: {
    Tomato: {
      id: "plant_tomato",
      spacing: 24,
      height: 72,
      width: 24,
      rootWidth: 24,
      color: "#ef4444",
      icon: "🍅",
      companions: ["Basil", "Marigold", "Oregano"],
      antagonists: [],
      habit: "Tall & Vertical",
      root: "Deep (> 12\")",
    },
    Basil: {
      id: "plant_basil",
      spacing: 10,
      height: 18,
      width: 12,
      rootWidth: 8,
      color: "#86efac",
      icon: "🌿",
      companions: ["Tomato", "Pepper", "Oregano"],
      antagonists: [],
      habit: "Bushy & Medium",
      root: "Shallow (< 6\")",
    },
    Marigold: {
      id: "plant_marigold",
      spacing: 10,
      height: 12,
      width: 10,
      rootWidth: 8,
      color: "#f59e0b",
      icon: "🌼",
      companions: ["Tomato", "Pepper", "Basil"],
      antagonists: [],
      habit: "Bushy & Medium",
      root: "Shallow (< 6\")",
    },
    Pepper: {
      id: "plant_pepper",
      spacing: 18,
      height: 28,
      width: 18,
      rootWidth: 16,
      color: "#facc15",
      icon: "🫑",
      companions: ["Basil", "Marigold", "Oregano"],
      antagonists: [],
      habit: "Bushy & Medium",
      root: "Medium (6-12\")",
    },
    Oregano: {
      id: "plant_oregano",
      spacing: 12,
      height: 18,
      width: 16,
      rootWidth: 12,
      color: "#4ade80",
      icon: "🌿",
      companions: ["Tomato", "Pepper", "Basil"],
      antagonists: [],
      habit: "Ground Cover",
      root: "Shallow (< 6\")",
    },
    Thyme: {
      id: "plant_thyme",
      spacing: 8,
      height: 8,
      width: 10,
      rootWidth: 8,
      color: "#22c55e",
      icon: "🌿",
      companions: ["Tomato", "Basil"],
      antagonists: [],
      habit: "Ground Cover",
      root: "Shallow (< 6\")",
    },
    Sage: {
      id: "plant_sage",
      spacing: 18,
      height: 24,
      width: 24,
      rootWidth: 18,
      color: "#6ee7b7",
      icon: "🌿",
      companions: ["Marigold", "Oregano"],
      antagonists: [],
      habit: "Bushy & Medium",
      root: "Medium (6-12\")",
    },
  },
  varieties: [
    {
      id: "t1",
      stableId: "var_tomato_better_boy",
      plantId: "plant_tomato",
      type: "Tomato",
      name: "Better Boy",
      spacing: 24,
      height: 72,
      width: 24,
      rootDepth: "Deep",
      rootWidth: 24,
      habit: "Indeterminate/Vining",
      description: "Classic slicing tomato with vigorous vertical growth.",
    },
    {
      id: "p1",
      stableId: "var_pepper_bell",
      plantId: "plant_pepper",
      type: "Pepper",
      name: "Bell",
      spacing: 18,
      height: 24,
      width: 18,
      rootDepth: "Medium",
      rootWidth: 16,
      habit: "Bushy",
      description: "Sweet bell pepper with a sturdy, compact canopy.",
    },
    {
      id: "p2",
      stableId: "var_pepper_jalapeno",
      plantId: "plant_pepper",
      type: "Pepper",
      name: "Jalapeno",
      spacing: 15,
      height: 30,
      width: 15,
      rootDepth: "Medium",
      rootWidth: 14,
      habit: "Bushy",
      description: "Moderately hot pepper with upright branching.",
    },
    {
      id: "b1",
      stableId: "var_basil_genovese",
      plantId: "plant_basil",
      type: "Basil",
      name: "Genovese",
      spacing: 10,
      height: 18,
      width: 12,
      rootDepth: "Shallow",
      rootWidth: 8,
      habit: "Bushy",
      description: "Classic sweet basil for culinary use.",
    },
    {
      id: "m1",
      stableId: "var_marigold_french_dwarf",
      plantId: "plant_marigold",
      type: "Marigold",
      name: "French Dwarf",
      spacing: 10,
      height: 12,
      width: 10,
      rootDepth: "Shallow",
      rootWidth: 8,
      habit: "Compact Bush",
      description: "Low marigold for edging and companion planting.",
    },
    {
      id: "o1",
      stableId: "var_oregano_greek",
      plantId: "plant_oregano",
      type: "Oregano",
      name: "Greek",
      spacing: 12,
      height: 18,
      width: 16,
      rootDepth: "Shallow",
      rootWidth: 12,
      habit: "Spreading",
      description: "Aromatic oregano with a low, spreading habit.",
    },
    {
      id: "th1",
      stableId: "var_thyme_english",
      plantId: "plant_thyme",
      type: "Thyme",
      name: "English",
      spacing: 8,
      height: 8,
      width: 10,
      rootDepth: "Shallow",
      rootWidth: 8,
      habit: "Ground Cover",
      description: "Compact thyme that forms a dense mat.",
    },
    {
      id: "s1",
      stableId: "var_sage_common",
      plantId: "plant_sage",
      type: "Sage",
      name: "Common",
      spacing: 18,
      height: 24,
      width: 24,
      rootDepth: "Medium",
      rootWidth: 18,
      habit: "Bushy",
      description: "Classic culinary sage with woody stems.",
    },
  ],
};

export const VEGGIE_METADATA = PLANT_CATALOG.plants;
export const SEED_VARIETY_LIBRARY = PLANT_CATALOG.varieties;
export const VEGGIE_TYPES = Object.keys(VEGGIE_METADATA);
